let data = [
  { id: 1, title: "6월 학사 일정 공지", category: "#공지사항", author: "관리자", lastEdited: "2024-06-01", comments: 5, content: "6월 주요 학사 일정 안내드립니다. 기말고사 일정은 6월 24일부터 6월 28일까지이며, 성적 입력 기간은 7월 1일부터 7월 5일까지입니다." },
  { id: 2, title: "자유게시판 테스트 글이에요!", category: "#자유게시판", author: "권태북", lastEdited: "2024-06-02", comments: 2, content: "학교 커뮤니티가 새로 열려서 한번 글 써봅니다ㅎㅎ 다들 좋은 하루 보내세요!" },
  { id: 3, title: "React useState 관련 질문", category: "#질문답변", author: "허재원", lastEdited: "2024-06-03", comments: 8, content: "useState로 배열을 관리할 때 기존 배열에 요소를 추가하려면 어떻게 해야 하나요? push 쓰면 안 된다고 들었어요." },
  { id: 4, title: "교내 프로젝트 팀 모집", category: "#프로젝트", author: "노지완", lastEdited: "2024-06-04", comments: 1, content: "교내 해커톤 참가를 위해 프론트엔드, 백엔드 각 1명씩 모집합니다. 관심 있는 분은 댓글 주세요!" },
  { id: 5, title: "자바 스터디 인원 모집", category: "#스터디", author: "장준민", lastEdited: "2024-06-05", comments: 4, content: "자바 기초 문법 및 객체지향 개념을 함께 공부할 사람 구합니다. 매주 수요일 점심시간에 진행할 예정이에요." },
  { id: 6, title: "학교 서버 점검 안내", category: "#공지사항", author: "관리자", lastEdited: "2024-06-06", comments: 3, content: "학교 네트워크 점검으로 6월 7일 오후 8시부터 9시까지 접속이 일시적으로 제한됩니다." },
  { id: 7, title: "자유게시판 활성화 시켜보자!", category: "#자유게시판", author: "김민수", lastEdited: "2024-06-07", comments: 6, content: "요즘 자유게시판에 글이 너무 없네요ㅠ 다들 근황이나 공부 꿀팁 좀 공유합시다!" },
  { id: 8, title: "JS 비동기 처리 질문", category: "#질문답변", author: "이수현", lastEdited: "2024-06-08", comments: 4, content: "Promise랑 async/await 중 뭐가 더 좋은지 잘 모르겠어요. 차이점이 뭔가요?" },
  { id: 9, title: "포트폴리오 프로젝트 공유", category: "#프로젝트", author: "박지윤", lastEdited: "2024-06-09", comments: 2, content: "리액트로 만든 개인 포트폴리오 웹사이트 공유합니다. 디자인 피드백 환영해요!" },
  { id: 10, title: "알고리즘 스터디 첫 모임 후기", category: "#스터디", author: "최지훈", lastEdited: "2024-06-10", comments: 9, content: "오늘 첫 모임 진행했어요! 문제 난이도가 생각보다 높았지만 같이 하니까 훨씬 재밌었습니다 :)" },
  { id: 11, title: "중간고사 성적 이의신청 안내", category: "#공지사항", author: "관리자", lastEdited: "2024-06-11", comments: 7, content: "성적 이의신청 기간은 6월 12일부터 6월 14일까지입니다. 각 과목 담당 교사에게 문의 바랍니다." },
  { id: 12, title: "오늘 급식 진짜 맛있네요ㅋㅋ", category: "#자유게시판", author: "정유나", lastEdited: "2024-06-12", comments: 3, content: "오늘 점심에 제육볶음 대박이었어요. 급식실 선생님들 감사합니다!" },
  { id: 13, title: "파이썬 리스트 슬라이싱 질문", category: "#질문답변", author: "이도윤", lastEdited: "2024-06-13", comments: 5, content: "리스트에서 특정 구간만 복사할 때 슬라이싱을 어떻게 쓰는 게 제일 효율적일까요?" },
  { id: 14, title: "교내 홈페이지 리뉴얼 프로젝트", category: "#프로젝트", author: "김하늘", lastEdited: "2024-06-14", comments: 4, content: "디자인 팀과 협업해서 새 UI를 적용 중입니다. 완성되면 미리보기 공유할게요!" },
  { id: 15, title: "HTML/CSS 스터디 모집", category: "#스터디", author: "박성준", lastEdited: "2024-06-15", comments: 6, content: "웹 기초부터 포트폴리오 페이지까지 함께 공부할 사람을 찾습니다. 프론트엔드 입문자 환영!" },
  { id: 16, title: "6월 동아리 정기회의 일정 공지", category: "#공지사항", author: "관리자", lastEdited: "2024-06-16", comments: 1, content: "6월 20일 오후 4시에 동아리 연합회의가 열립니다. 대표자는 필참 바랍니다." },
  { id: 17, title: "졸업앨범 사진 언제 찍나요?", category: "#자유게시판", author: "한지민", lastEdited: "2024-06-17", comments: 8, content: "졸업앨범 촬영 일정 아시는 분 있나요? 아직 공지가 안 올라온 것 같아요." },
  { id: 18, title: "Node.js 모듈 import 오류 질문", category: "#질문답변", author: "이진호", lastEdited: "2024-06-18", comments: 2, content: "require로는 되는데 import 쓰면 에러가 나요. 혹시 package.json 설정이 문제일까요?" },
  { id: 19, title: "학교 홈페이지 메인 배너 작업 중", category: "#프로젝트", author: "김도현", lastEdited: "2024-06-19", comments: 3, content: "디자인 반영 중인데 배너 이미지 피드백 환영합니다!" },
  { id: 20, title: "스터디 발표 연습 자료 공유", category: "#스터디", author: "오세훈", lastEdited: "2024-06-20", comments: 5, content: "이번 주 발표자 분들 참고하시라고 템플릿 올립니다. 필요하신 분은 다운로드해주세요." },
  { id: 21, title: "7월 학사 일정 공지", category: "#공지사항", author: "관리자", lastEdited: "2024-06-21", comments: 2, content: "7월 학사 일정 안내드립니다. 방학식, 학기말 평가 일정 포함." },
  { id: 22, title: "자유게시판 사진 공유", category: "#자유게시판", author: "조민지", lastEdited: "2024-06-22", comments: 7, content: "이번 주 체육대회 사진 올려요! 다들 사진 확인해주세요." },
  { id: 23, title: "CSS 그리드 질문", category: "#질문답변", author: "정하윤", lastEdited: "2024-06-23", comments: 3, content: "CSS grid에서 열 간격을 일정하게 맞추는 방법이 있을까요?" },
  { id: 24, title: "React 프로젝트 팀 모집", category: "#프로젝트", author: "이승현", lastEdited: "2024-06-24", comments: 9, content: "React와 Firebase를 활용한 팀 프로젝트를 같이 진행할 팀원 모집합니다." },
  { id: 25, title: "스터디 후기 공유", category: "#스터디", author: "박서연", lastEdited: "2024-06-25", comments: 4, content: "지난 주 스터디 진행 내용과 느낀 점 공유합니다. 자료 참고하세요." },
  { id: 26, title: "학교 네트워크 점검 안내", category: "#공지사항", author: "관리자", lastEdited: "2024-06-26", comments: 3, content: "6월 27일 오후 6시부터 7시까지 학교 네트워크 점검이 예정되어 있습니다." },
  { id: 27, title: "자유게시판 근황 공유", category: "#자유게시판", author: "최민호", lastEdited: "2024-06-27", comments: 6, content: "요즘 날씨가 좋아서 점심시간에 산책 다녀왔습니다." },
  { id: 28, title: "Python 함수 질문", category: "#질문답변", author: "윤지호", lastEdited: "2024-06-28", comments: 8, content: "함수 안에서 변수를 글로벌로 사용하고 싶으면 어떻게 해야 하나요?" },
  { id: 29, title: "Node.js 서버 배포 프로젝트", category: "#프로젝트", author: "이서연", lastEdited: "2024-06-29", comments: 2, content: "Node.js 기반 서버 배포 프로젝트 진행 중입니다. 배포 방법 피드백 부탁드립니다." },
  { id: 30, title: "스터디 과제 공유", category: "#스터디", author: "김태형", lastEdited: "2024-06-30", comments: 5, content: "이번 주 과제 파일 올립니다. 꼭 확인해주세요." },
  { id: 31, title: "중간고사 시간표 공지", category: "#공지사항", author: "관리자", lastEdited: "2024-07-01", comments: 4, content: "중간고사 시간표 공지드립니다. 각 교시별 시험실 확인 필수." },
  { id: 32, title: "자유게시판 영화 추천", category: "#자유게시판", author: "박하린", lastEdited: "2024-07-02", comments: 3, content: "최근 본 영화 추천해요! 재밌게 본 작품 공유 부탁드립니다." },
  { id: 33, title: "JavaScript 배열 함수 질문", category: "#질문답변", author: "정동현", lastEdited: "2024-07-03", comments: 7, content: "map, filter, reduce의 차이와 효율적인 사용법 질문드립니다." },
  { id: 34, title: "Vue.js 프로젝트 진행중", category: "#프로젝트", author: "이시윤", lastEdited: "2024-07-04", comments: 1, content: "Vue.js 기반 개인 프로젝트 진행 중입니다. UI 피드백 요청드립니다." },
  { id: 35, title: "스터디 발표 연습 자료", category: "#스터디", author: "김예은", lastEdited: "2024-07-05", comments: 5, content: "다음 주 발표 준비 자료 올립니다. 참고하시길 바랍니다." },
  { id: 36, title: "방학식 안내", category: "#공지사항", author: "관리자", lastEdited: "2024-07-06", comments: 2, content: "7월 10일에 방학식이 있습니다. 일정 확인 바랍니다." },
  { id: 37, title: "자유게시판 근황 토론", category: "#자유게시판", author: "최준호", lastEdited: "2024-07-07", comments: 6, content: "최근 학내 행사 후기와 사진 공유합니다." },
  { id: 38, title: "CSS Flexbox 질문", category: "#질문답변", author: "윤서진", lastEdited: "2024-07-08", comments: 3, content: "Flexbox에서 justify-content와 align-items의 차이가 궁금합니다." },
  { id: 39, title: "Spring Boot 프로젝트 공유", category: "#프로젝트", author: "박도윤", lastEdited: "2024-07-09", comments: 8, content: "Spring Boot로 만든 간단한 게시판 프로젝트 공유합니다." },
  { id: 40, title: "스터디 스크립트 자료", category: "#스터디", author: "이예진", lastEdited: "2024-07-10", comments: 5, content: "이번 주 스터디 진행 스크립트 자료 올립니다." },
  { id: 41, title: "기말고사 일정 공지", category: "#공지사항", author: "관리자", lastEdited: "2024-07-11", comments: 7, content: "기말고사 일정 안내드립니다. 시험 시간, 장소 확인 필수." },
  { id: 42, title: "자유게시판 여행 후기", category: "#자유게시판", author: "김수연", lastEdited: "2024-07-12", comments: 2, content: "이번 여름 여행 후기 공유합니다. 사진 포함!" },
  { id: 43, title: "React Hooks 질문", category: "#질문답변", author: "이재훈", lastEdited: "2024-07-13", comments: 9, content: "useEffect와 useLayoutEffect 차이와 사용 시 주의점 질문드립니다." },
  { id: 44, title: "Angular 프로젝트 진행중", category: "#프로젝트", author: "정하늘", lastEdited: "2024-07-14", comments: 4, content: "Angular로 간단한 Todo 프로젝트 진행 중입니다." },
  { id: 45, title: "스터디 발표 자료 공유", category: "#스터디", author: "박유진", lastEdited: "2024-07-15", comments: 6, content: "발표 자료 올립니다. 필요하신 분은 확인해주세요." },
  { id: 46, title: "학교 공지사항 안내", category: "#공지사항", author: "관리자", lastEdited: "2024-07-16", comments: 3, content: "학교 공지사항 확인 바랍니다." },
  { id: 47, title: "자유게시판 오늘의 일상", category: "#자유게시판", author: "이승민", lastEdited: "2024-07-17", comments: 5, content: "오늘 하루 일상 기록 공유합니다." },
  { id: 48, title: "JS 이벤트 처리 질문", category: "#질문답변", author: "김지후", lastEdited: "2024-07-18", comments: 4, content: "onclick과 addEventListener 차이와 best practice 질문드립니다." },
  { id: 49, title: "React 프로젝트 배포", category: "#프로젝트", author: "정민서", lastEdited: "2024-07-19", comments: 8, content: "React 프로젝트 Netlify 배포 경험 공유합니다." },
  { id: 50, title: "스터디 마무리 자료", category: "#스터디", author: "최유찬", lastEdited: "2024-07-20", comments: 2, content: "이번 주 스터디 마무리 자료 올립니다." }
];

export default data;
